spring:
  application:
    name: blog Api
  datasource:
    url: jdbc:h2:mem:blog
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console